[llm]
model_name = ollama_chat/qwen3:latest

[mcp]
# Supported transports: stdio, http
# For stdio: use command and args (e.g., command=scale-mcp-server)
# For http use url (e.g., url=http://127.0.0.1:8000/mcp)
# transport = stdio
# command = <path/>.local/bin/uv
# args = --directory </path/to/ibm-storage-scale-mcp-server> run scale-mcp-server --transport stdio
transport = http
url = http://127.0.0.1:8000/mcp


[logging]
level = INFO
format = json
file_path = logs/agent.log
max_bytes = 10485760
backup_count = 5
